name: Branch-Based Approval Workflow

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'
      - 'main'
  workflow_dispatch:

jobs:
  trigger-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Approvers Based on Branch
        id: approvers
        run: |
          branch_name=${GITHUB_REF##*/}
          if echo "$branch_name" | grep -qE '^feature/'; then
            echo "hamza.koc@deop.ca" > approvers.txt
          elif echo "$branch_name" | grep -qE '^hotfix/'; then
            echo "hamza.koc@deop.ca" > approvers.txt
          elif [[ "$branch_name" == "main" ]]; then
            echo "hamza.koc@deop.ca" > approvers.txt
          else
            echo "hamza.koc@deop.ca" > approvers.txt
          fi
          approvers=$(cat approvers.txt)
          echo "approvers=$approvers" >> $GITHUB_ENV

      - name: Request PR Approval
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post-Approval Actions
        run: |
          echo "Approval completed for branch: ${GITHUB_REF##*/}"
